plugins {
    id 'net.neoforged.gradle.userdev' version '7.0.+'
}

base {
    archivesName = "${rootProject.archives_base_name}-1.21.4-neoforge"
}

version = rootProject.mod_version
group = rootProject.maven_group

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

minecraft {
    mappings channel: 'official', version: '1.21.4'
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')
    runs {
        server {
            workingDirectory project.file('run')
            mods {
                qlogin {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets {
    main {
        java {
            srcDir "src/main/java"
        }
        resources {
            srcDir "src/main/resources"
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "net.neoforged:neoforge:${rootProject.neoforge_1_21_4}"

    implementation 'org.xerial:sqlite-jdbc:' + rootProject.sqlite_jdbc_version
}

jar {
    manifest {
        attributes([
            'Specification-Title'     : 'QLogin',
            'Specification-Vendor'    : 'aqing',
            'Specification-Version'   : '1',
            'Implementation-Title'    : 'QLogin-1.21.4-NeoForge',
            'Implementation-Version'  : rootProject.mod_version,
            'Implementation-Vendor'   : 'aqing'
        ])
    }
}

processResources {
    inputs.property "version", rootProject.mod_version
    filteringCharset "UTF-8"
    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": rootProject.mod_version
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = 'UTF-8'
    it.options.release = 21
}

// Bundle SQLite driver into jar
jar {
    from {
        configurations.runtimeClasspath.findAll {
            it.name.contains('sqlite')
        }.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}