modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="qlogin"
version="${version}"
displayName="QLogin"
logoFile="assets/qlogin/icon.png"
credits="aqing"
authors="aqing"
description="""
QLogin player login authentication system - Minecraft 1.21.5 (NeoForge)
"""

[[dependencies.qlogin]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.5,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.qlogin]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.5,1.21.6)"
    ordering="NONE"
    side="SERVER"