modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL=""

[[mods]]
modId="qlogin"
version="${version}"
displayName="QLogin"
logoFile="assets/qlogin/icon.png"
credits="aqing"
authors="aqing"
description="""
QLogin player login authentication system - Minecraft 1.18.2 (Forge)
"""

[[dependencies.qlogin]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.qlogin]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="SERVER"