plugins {
    id 'fabric-loom' version '1.9-SNAPSHOT'
}

base {
    archivesName = "${rootProject.archives_base_name}-1.19.1"
}

sourceSets {
    main {
        java {
            srcDir "src/main/java"
        }
        resources {
            srcDir "src/main/resources"
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.mc_1_19_1}"
    mappings "net.fabricmc:yarn:${rootProject.yarn_1_19_1}:v2"
    modImplementation "net.fabricmc:fabric-loader:${rootProject.loader_1_19_1}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_1_19_1}"
    include "org.xerial:sqlite-jdbc:${rootProject.sqlite_jdbc_version}"
}

loom {
    mixin.defaultRefmapName = "QLogin-1.19.1-refmap.json"
}

processResources {
    inputs.property "version", project.version
    filteringCharset "UTF-8"
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}