modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
issueTrackerURL=""

[[mods]]
modId="qlogin"
version="${version}"
displayName="QLogin"
logoFile="assets/qlogin/icon.png"
credits="aqing"
authors="aqing"
description="""
QLogin player login authentication system - Minecraft 1.17.1 (Forge)
"""

[[dependencies.qlogin]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.qlogin]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="SERVER"