modLoader="javafml"
loaderVersion="[49,)"
license="MIT"
issueTrackerURL=""

[[mods]]
modId="qlogin"
version="${version}"
displayName="QLogin"
logoFile="assets/qlogin/icon.png"
credits="aqing"
authors="aqing"
description="""
QLogin player login authentication system - Minecraft 1.20.4 (Forge)
"""

[[dependencies.qlogin]]
    modId="forge"
    mandatory=true
    versionRange="[49,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.qlogin]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.4,1.20.5)"
    ordering="NONE"
    side="SERVER"